---
# tasks file for glusterfs.infra
- name: Add firewall rules
  import_role:
    name: "glusterfs.infra/roles/firewall_config"
  when: glusterfs_infra_fw_state is defined
  tags:
    - firewall

- name: Configure the bricks
  import_role:
    name: "glusterfs.infra/roles/backend_setup"
  tags:
    - backend_setup
