---
- name: Prepare
  hosts: all
  tasks:
  - name: Clean up loopback devices
    command: "losetup -D"
  - name: Remove data files
    file:
      path: "{{item.1}}"
      state: absent
    with_items:
      - data0
      - data1
  - name: Remove volume groups
    lvol:
      vg: vg_vdb
      state: absent
    pvs: /dev/loop0
  - name: Remove thinpool
    lvol:
      thinpool: vg_vdc
      state: absent
    pvs: /dev/loop1
