---
- name: Setting up backend
  remote_user: root
  hosts: gluster_servers
  gather_facts: false

  vars:
     # Set a disk type - Default: JBOD
     # Options: JBOD, RAID6, RAID10
     gluster_infra_disktype: RAID6

     # RAID6 and RAID10 diskcount
     gluster_infra_diskcount: 10

     # Stripe unit size always in KiB
     gluster_infra_stripe_unit_size: 128

     # Variables for creating volume group
     #
     gluster_infra_volume_groups:
        - { vgname: 'vg_sdb', pvname: '/dev/sdb' }
        - { vgname: 'vg_sdc', pvname: '/dev/sdc' }

     # Create thinpools
     gluster_infra_thinpools:
       - {vgname: 'vg_sdb', thinpoolname: 'foo_thinpool', thinpoolsize: '100G', poolmetadatasize: '16G'
       - {vgname: 'vg_sdc', thinpoolname: 'bar_thinpool', thinpoolsize: '500G', poolmetadatasize: '16G'

     # Create a thin volume
     gluster_infra_lv_logicalvols:
        - { vgname: 'vg_sdc', lvname: 'glusterstore_thinlv', lvsize: '500G' }

     # Create a thick volume name
     gluster_infra_thick_lvs:
       - { vgname: 'vg_sdb', lvname: 'thick_lv1', size: '100G' }
       - { vgname: 'vg_sdc', lvname: 'thick_lv2', size: '500G' }

     # Mount the devices
     gluster_infra_mount_devices:
        - { path: '/mnt/thinv',  vgname: 'vg_sdb', lv: glusterstore_thinlv }
        - { path: '/mnt/thicklv1', vgname: 'vg_sdc', lv: 'thick_lv1' }
        - { path: '/mnt/thicklv2', vgname: 'vg_sdc', lv: 'thick_lv2' }

  roles:
     - gluster.infra
