---
- name: Setting up backend with VDO
  remote_user: root
  hosts: vdos
  gather_facts: false

  vars:
     # Create a vdo
     gluster_infra_vdo:
        - { name: 'foo', device: '/dev/vdb' }
        - { name: 'bar', device: '/dev/vdc' }

     gluster_infra_disktype: RAID10

     # RAID6 and RAID10 diskcount
     gluster_infra_diskcount: 10
     gluster_infra_stripe_unit_size: 128

     # Create thinpools
     gluster_infra_thinpools:
       - {vgname: 'vg_sdb', thinpoolname: 'foo_thinpool', thinpoolsize: '100G', poolmetadatasize: '16G'
       - {vgname: 'vg_sdc', thinpoolname: 'bar_thinpool', thinpoolsize: '500G', poolmetadatasize: '16G'

     gluster_infra_lv_logicalvols:
        - { lvname: 'thin_lv1', vgname: 'vg_sdb', lvsize: '500G' }
        - { lvname: 'thin_lv2', vgname: 'vg_sdc', lvsize: '500G' }

     # Mount the devices
     gluster_infra_mount_devices:
        - { path: '/mnt/thinv1', vgname: 'vg_sdb', lv: 'thin_lv1' }
        - { path: '/mnt/thinv2', vgname: 'vg_sdc', lv: 'thin_lv2' }

  roles:
    - gluster.infra
