- name: Setting up backend
  remote_user: root
  hosts: vdos
  gather_facts: false

  # gluster-ansible -i inventory_file cache_setup.yml --tags cachesetup

  vars:
     # Variables for creating volume group
     gluster_infra_volume_groups:
        - {vgname: 'glusterfs_vg', pvname: '/dev/mapper/foo,/dev/mapper/bar'}

     gluster_infra_ssd_disk: /dev/vdd
     gluster_infra_lv_cachelvsize: 100M

  roles:
      - gluster.infra
