---
# CLI: ansible-playbook -i inventory hc_backend.yml
# Set up backend for the hyperconverged setup
- name: Setting up backend with VDO
  remote_user: root
  hosts: vdos
  gather_facts: false

  vars:
     # Create a vdo
     gluster_infra_vdo:
        - { name: 'hc_vdo', device: '/dev/vdb' }

     # Disk parameters
     gluster_infra_disktype: RAID6
     gluster_infra_diskcount: 10
     gluster_infra_stripe_unit_size: 128

     # Set the size for thick volume
     gluster_infra_thick_lvs:
       - { vgname: 'vg_sdb', lvname: 'hc_engine', size: '20G' }

     # Create thin logical volumes
     gluster_infra_lv_logicalvols:
        - { vgname: 'vg_sdb', lvname: 'hc_images', lvsize: '500G' }
        - { vgname: 'vg_sdc', lvname: 'hc_data', lvsize: '500G' }

     # Setup cache on the disks
     gluster_infra_ssd_disk: /dev/vdd
     gluster_infra_ssd_vgname: 'vg_sdc'
     gluster_infra_lv_cachelvsize: 20G

     # Mount the devices
     gluster_infra_mount_devices:
        - { path: '/mnt/images', vgname: 'vg_sdb', lv: hc_images }
        - { path: '/mnt/engine', vgname: 'vg_sdc', lv: glusterfs_thicklv }
        - { path: '/mnt/data',   vgname: 'vg_sdc', lv: hc_data   }

  roles:
    - gluster.infra
