---
# A vdo is created an will be used for setting up bricks instead of physical
# volumes

# Initialize vdo_devs to empty list, vdo_devs would not not be initialized if
# search fails
- name: Initialize vdo_devs array
  set_fact:
     vdo_devs: []

# Get the list of volume groups created on vdo disks
# This is a bit hacky, we rely on pvname to get vdo disks
- name: Record VDO devices (if any)
  set_fact:
     vdo_devs: "{{ vdo_devs|default([]) + [ item.vgname ] }}"
  with_items: "{{ gluster_infra_volume_groups }}"
  when: item.pvname is search("/dev/mapper/")

- name: Create a vdo disk
  import_tasks: vdo_create.yml
  when: gluster_infra_vdo is defined
  tags:
    - vdocreate

- name: Create a volume group
  import_tasks: vg_create.yml
  when: gluster_infra_volume_groups is defined
  tags:
     - vgcreate

# If a thick volume is requested for the same vg
- name: Create a thick logical volume
  import_tasks: thick_lv_create.yml
  when: gluster_infra_thick_lvs is defined
  tags:
    - thickvol

# Create a thinpool for the given volume group
- name: Create thin pool
  import_tasks: thin_pool_create.yml
  when: gluster_infra_thinpools is defined
  tags:
    - thinpool

# Create a thin volume
- name: Create thin logical volume
  import_tasks: thin_volume_create.yml
  when: gluster_infra_lv_logicalvols is defined
  tags:
    - thinvol

# Setup cache on the given SSD
- name: Setup cache
  import_tasks: cache_setup.yml
  when: gluster_infra_cache_vars is defined
  tags:
    - cachesetup

# Create a filesystem on the disks.
- name: Create a filesystem on the disks
  import_tasks: fscreate.yml
  when: gluster_infra_lv_logicalvols is defined or
        gluster_infra_thick_lvs is defined
  tags:
    - fscreate

# Mount the devices
- name: Mount the devices
  import_tasks: mount.yml
  when: gluster_infra_mount_devices is defined
  tags:
    - mount
