---
# Only XFS is supported in GlusterFS

# Create mount directories if not already present
- name: Create mount directories if not already present
  file:
     path: "{{ item.path }}"
     state: directory
  with_items: "{{ gluster_infra_mount_devices }}"

# In case of vdo disks, use different mount options
- name: Set mount options for VDO
  set_fact:
     vdo_opts: ",x-systemd.requires=vdo.service"
  when: gluster_infra_vdo is defined

- name: Mount the devices
  mount:
     path: "{{ item.path }}"
     state: mounted
     fstype: xfs
     opts: "inode64,noatime,nodiratime{{ vdo_opts|default('')}}"
     src: "/dev/{{item.vgname}}/{{item.lvname}}"
  with_items: "{{ gluster_infra_mount_devices }}"

- name: Set Gluster specific SeLinux context on the bricks
  sefcontext:
     target: "{{ item.path }}"
     setype: glusterd_brick_t
     state: present
  with_items: "{{ gluster_infra_mount_devices }}"

- name: restore file(s) default SELinux security contexts
  command: restorecon -Rv "{{ item.path }}"
  with_items: "{{ gluster_infra_mount_devices }}"
