---
# Create a thin logical volume. A thinpool should already have been created by
# now. There can be more than one thinvolume on a thinpool

- name: Create thin logical volume
  lvol:
     state: present
     vg: "{{ glusterfs_infra_vg_name }}"
     lv: "{{ item.lvname }}"
     thinpool: "{{ glusterfs_infra_lv_thinpoolname }}"
     size: "{{ item.lvsize }}"
  with_items: "{{ glusterfs_infra_lv_logicalvols }}"