---
- name: Create VDO with specified size
  vdo:
      name: "{{ item.name }}"
      device: "{{ item.device }}"
      state: "{{ glusterfs_infra_vdo_state }}"
      activated: "{{ glusterfs_infra_vdo_activated | default('yes') }}"
      running: "{{ glusterfs_infra_vdo_running | default('yes') }}"
      logicalsize: "{{ item.logicalsize | default('') }}"
      compression: "{{ glusterfs_infra_vdo_compression | default('enabled') }}"
      blockmapcachesize:
          "{{ glusterfs_infra_vdo_blockmapcachesize | default('128M') }}"
      readcache: "{{ glusterfs_infra_vdo_readcache | default('disabled') }}"
      readcachesize: "{{ glusterfs_infra_vdo_readcachesize | default('0') }}"
      emulate512: "{{ glusterfs_infra_vdo_emulate512 | default('off') }}"
      slabsize: "{{ glusterfs_infra_vdo_slabsize | default('2G') }}"
      writepolicy: "{{ glusterfs_infra_vdo_writepolicy | default('sync') }}"
      indexmem: "{{ glusterfs_infra_vdo_indexmem | default('0.25') }}"
      indexmode: "{{ glusterfs_infra_vdo_indexmode | default('dense') }}"
      ackthreads: "{{ glusterfs_infra_vdo_ackthreads | default('1') }}"
      biothreads: "{{ glusterfs_infra_vdo_biothreads | default('4') }}"
      cputhreads: "{{ glusterfs_infra_vdo_cputhreads | default('2') }}"
      logicalthreads: "{{ glusterfs_infra_vdo_logicalthreads | default('1') }}"
      physicalthreads:
          "{{ glusterfs_infra_vdo_physicalthreads | default('1') }}"
  with_items: "{{ glusterfs_infra_vdo }}"
