---
# We have to set the dataalignment for physical volumes, and physicalextentsize
# for volume groups. For JBODs we use a constant alignment value of 256K
# however, for RAID we calculate it by multiplying the RAID stripe unit size
# with the number of data disks. Hence in case of RAID stripe_unit_size and data
# disks are mandatory parameters.

# TODO: Handle invalid disktype and throw usage message

# Set data alignment for JBODs, by default it is 256K. This set_fact is not
# needed if we can always assume 256K for JBOD, however we provide this extra
# variable to override it.
- name: Set PV data alignment for JBOD
  set_fact:
     pv_dataalign: "{{ glusterfs_infra_dalign | default('256K') }}"
  when: glusterfs_infra_disktype == 'JBOD'

# Set data alignment for RAID
# We need KiB: ensure to keep the trailing `K' in the pv_dataalign calculation.
- name: Set PV data alignment for RAID
  set_fact:
     pv_dataalign: >
        {{ glusterfs_infra_diskcount|int *
           glusterfs_infra_stripe_unit_size|int }}K
  when: >
      glusterfs_infra_disktype == 'RAID6' or
      glusterfs_infra_disktype == 'RAID10'

# Set pesize for RAID disktypes while creating a volume group
# By default the `lvg' module expects size in MiB: divide by 1024.
# Once issue: https://github.com/ansible/ansible/issues/38103 is resolved the
# division by 1024 can be removed.
- name: Set VG physical extent size for RAID
  set_fact:
     vg_pesize: >
         {{ glusterfs_infra_diskcount|int *
            glusterfs_infra_stripe_unit_size|int / 1024 }}
  when: >
     glusterfs_infra_disktype == 'RAID6' or
     glusterfs_infra_disktype == 'RAID10'

# If the disk is vdo, generate the vdo device(s)
# A bit kludgy
- name: Set the vdo disks
  set_fact:
     glusterfs_infra_pvs:
         "/dev/mapper/{{glusterfs_infra_vdo|map(attribute='name')|
                        join(',/dev/mapper/') }}"
  when: glusterfs_infra_vdo is defined

# Tasks to create a volume group
# The devices in `pvs' can be a regular device or a VDO device
- name: Create volume group - "{{glusterfs_infra_vg_name}}"
  lvg:
     state: present
     vg: "{{ glusterfs_infra_vg_name }}"
     pvs: "{{ glusterfs_infra_pvs }}"
     pv_options: "--dataalignment {{ pv_dataalign }}"
     # pesize is 4m by default for JBODs
     pesize: "{{ vg_pesize|int | default(4) }}"
