---
- name: Reset the bricks
  remote_user: root
  gather_facts: no
  hosts: all
  vars:
     gluster_volumes: testvol
     gluster_infra_reset_mnt_paths:
       - /mnt/brick0
       - /mnt/brick1
     gluster_infra_reset_volume_groups:
       - vg_vdb
       - vg_vdc

  pre_tasks:
    - name: Delete Gluster volume(s)
      gluster_volume:
         state: absent
         name: "{{ item }}"
      with_items: "{{ gluster_volumes }}"
      run_once: true

  roles:
    - gluster.infra
